### ISSUE TITLE
Running into error on startup

### ISSUE THREAD

**Issue by lukasschachner** [thomasfn/ScreepsDotNet#3]
Im currently trying to get your Basic Example running on a local private server. Sadly im running into an error when starting the dotnet runtime:
```
TypeError: Cannot read property 'location' of undefined
```
I removed the try/catch block to track it down.
It is saying that the issue is happening on line `DotNet.createRuntime:13397:9`

**Comment by thomasfn** [comment]
Are you using the most up-to-date version of the private server? The one bundled with the steam client is horrible outdated and has missing apis. I'd recommend using [screeps-launcher](https://github.com/screepers/screeps-launcher) instead.

**Comment by thomasfn** [comment]
Closing as no further update from op for a while. Please open a new issue or comment back on this one if this issue persists or reoccurs
