### ISSUE TITLE
INIT: fatal error initialising runtime TypeError: self is undefined

### ISSUE THREAD

**Issue by nwen-cu** [thomasfn/ScreepsDotNet#4]
I followed the quickstart guide and got my bundled code deployed on world (both simulation and real world). But when initializing the runtime, it gives the following issue and causes the initialization repeatedly triggered

> [11:00:32 PM]
#1: INIT state refreshed, beginning init sequence
[11:00:32 PM]
#1 INIT: loaded js dependencies (0ms)
[11:00:32 PM]
DOTNET  loaded 8 items from the manifest, totalling 5897 KiB of data
[11:00:32 PM]
DOTNET  PROFILE decodeManifest 0 ms
[11:00:32 PM]
DOTNET  PROFILE decodeManifest (b64) 0 ms
[11:00:32 PM]
DOTNET  PROFILE decodeManifest (inflate) 0 ms
[11:00:32 PM]
DOTNET  DEBUG:  creating dotnet runtime...
[11:00:32 PM]
**#1 INIT: fatal error initialising runtime TypeError: self is undefined**
[11:00:32 PM]
#1 INIT: shutting down and starting again
[11:00:33 PM]
DOTNET  PROFILE loop 0 ms
[11:00:34 PM]
DOTNET  PROFILE loop 0 ms
[11:00:35 PM]
DOTNET  PROFILE loop 0 ms
[11:00:36 PM]
DOTNET  PROFILE loop 0 ms 
...
And repeat the exact same output indefinitely.

**Comment by thomasfn** [comment]
As with #3, can you confirm that the environment you are trying to run in is not an outdated version of the private server? Unfortunately this error isn't really much to go on without some sort of stack trace. It is odd however that the profiling messages are all reporting 0ms - I wonder if it can't load the other js files for some reason. Is the total file size underneath the 5mb script size limit?

**Comment by nevercast** [comment]
> totalling 5897 KiB of data 

Could this be an inflated Debug build ?

**Comment by thomasfn** [comment]
Closing as no further update from op for a while. Please open a new issue or comment back on this one if this issue persists or reoccurs
